config/routes.rb
Rails.application.routes.draw do

  root 'application#index'
  match '/dispatch' , :to => 'application#dispatch' , :via => 'get'
  match '/dispatch' , :to => 'application#notify_couriers' , :via => 'post'
  match '/schedule' , :to => 'application#schedule', :via => 'get'
  match '/schedule' , :to => 'application#scheduled_notification', :via => 'post'

  match '/package/new' , :to => 'package#new' , :via => 'get'
  match '/package/new' , :to => 'package#create' , :via => 'post'

  match '/email/new' , :to => 'email#new' , :via => 'get'
  match '/email/new' , :to => 'email#create' , :via => 'post'

  match '/*paths' => redirect('/') , :via => [:get, :post]

end

app/controllers/application_controller.rb
require 'clockwork'
require 'notify_couriers_job'

class ApplicationController < ActionController::Base
  include PackageHelper
  include EmailHelper
  include Clockwork
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery :with => :exception
  http_basic_authenticate_with :name => "admin", :password => "alphabetagamma"

  # Runs a notify couriers action for application : send out emails to registered couriers with package details
  # Params: city db id for application controller
  # - command :: command line string to be executed by the system
  # - outhandler :: +Proc+ object that takes a pipe object as first and only param (may be nil)
  # - errhandler :: +Proc+ object that takes a pipe object as first and only param (may be nil)
  def notify_couriers
    @current_time = Time.zone.now

    @packages = find_packages(application_params[:city_db_id])

    @emails = find_emails(application_params[:city_db_id])

    ## Create list of recipients as array of strings
    @recipients = []
    @emails.each do |email|
      @recipients << email.email_value
    end

    # Tell the Emailer to send a notification email to all couriers
    Emailer.packages_notification(@current_time,@packages,@recipients).deliver
  end

  # Runs a notify couriers action for application at specific time : send out emails to registered couriers with package details
  # Params: city db id & schedule times for dispatcher
  # - command :: command line string to be executed by the system
  # - outhandler :: +Proc+ object that takes a pipe object as first and only param (may be nil)
  # - errhandler :: +Proc+ object that takes a pipe object as first and only param (may be nil)
  def scheduled_notification
    @scheduled_time =  params[:time]
    @city_db_id =  application_params[:city_db_id]

    @scheduled_time.each do |time|
      Delayed::Job.enqueue(NotifyCouriersJob.new(@city_db_id), :run_at => time)
    end
  end

  private
  # Private method available to application controller methods : used for strongly checking paramaters to various actions inside controller
  # Params: permitted city db id for application controller
  # - command :: command line string to be executed by the system
  # - outhandler :: +Proc+ object that takes a pipe object as first and only param (may be nil)
  # - errhandler :: +Proc+ object that takes a pipe object as first and only param (may be nil)
  def application_params
    params.require(:application).permit(:city_db_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/views/application/dispatch.html.erb
<div>
  <h2>Dispatch Packages from City</h2>
</div>
<div>
  <form id="search" action="/dispatch" method="post">
    <%= hidden_field_tag :authenticity_token, form_authenticity_token -%>
    City Id: <input type="text" name="application[city_db_id]"> <br>
    <input type="submit" value="Submit">
  </form>
</div>

app/views/application/error.html.erb
<div>
  <h1>Something went wrong. Try again</h1>
  <h4><%= @errors %></h4>
  <h3>Current Time: <%= Time.zone.now %></h3>
</div>
<div>
  <%= link_to "Homepage", root_path %>
</div>

app/views/application/index.html.erb
<div>
  <h1>Welcome to the Package Tracking App</h1>
  <h2>We are working to make your life easier</h2>
  <h3>Current Time: <%= Time.zone.now %></h3>
</div>
<div>
  <%= link_to "Send a Package", package_new_path %>
</div>
<div>
  <%= link_to "Register as Courier", email_new_path %>
</div>
<div>
  <%= link_to "Dispatch Packages(Admin method)", dispatch_path %>
</div>
<div>
  <%= link_to "Scheduled Dispatch Packages(Admin method)", schedule_path %>
</div>

app/views/application/notify_couriers.html.erb
<h3> Current time: <%= @current_time %> </h3>
<% if @packages.size > 0 %>
    <h4> Packages available to be delivered in the city: <%= @packages.size %> </h4>
    <h5> Packages Detail </h5>
    <ul>
      <% @packages.each do |package| %>
      <li> Package Id: <%= package.id %></li>
      <% end %>
    </ul>
<% else %>
    <h4> No Package available to be delivered in the city</h4>
<% end %>

<% if @emails.size > 0 %>
    <h4> Couriers available to deliver the packages in the city: <%= @emails.size %></h4>
    <h5> Couriers Detail </h5>
    <ul>
      <% @emails.each do |email| %>
          <li> Email Address: <%= email.email_value %></li>
      <% end %>
    </ul>
<% else %>
    <h4> Sorry! No courier available to deliver the packages in the city</h4>
<% end %>

<div>
  <br><%= link_to "Dispatch Packages", dispatch_path %>
  <br><%= link_to "Homepage", root_path %>
</div>

app/views/application/schedule.html.erb
<div>
  <h2>Dispatch Packages from City at scheduled time</h2>
  <h3>Current Time: <%= Time.zone.now %></h3>
</div>
<div>
  <form id="search" action="/schedule" method="post">
    <%= hidden_field_tag :authenticity_token, form_authenticity_token -%>
    City Id: <input type="text" name="application[city_db_id]"> <br>
    Scheduled Time:
    <select multiple name="time[]" id="time">
      <option value="5:00">5:00 AM</option>
      <option value="5:30">5:30 AM</option>
      <option value="6:00">6:00 AM</option>
      <option value="6:30">6:30 AM</option>
      <option value="7:30">7:30 AM</option>
      <option value="9:00">9:00 AM</option>
      <option value="10:00">10:00 AM</option>
      <option value="12:00">12:00 PM</option>
      <option value="13:00">1:00 PM</option>
      <option value="14:00">2:00 PM</option>
      <option value="15:00">3:00 PM</option>
      <option value="16:00">4:00 PM</option>
      <option value="17:00">5:00 PM</option>
      <option value="18:00">6:00 PM</option>
      <option value="19:00">7:00 PM</option>
      <option value="19:30">7:30 PM</option>
      <option value="20:30">8:30 PM</option>
      <option value="20:45">8:45 PM</option>
      <option value="21:45">9:45 PM</option>
      <option value="22:30">10:30 PM</option>
      <option value="23:15">11:15 PM</option>
      <option value="23:45">11:45 PM</option>
    </select><br>
    <input type="submit" value="Submit">
  </form>
</div>

app/views/application/scheduled_notification.html.erb
<div>
  <h2>Dispatch Packages from City <%= @city_db_id %> at following scheduled times:</h2>
  <% @scheduled_time.each do |time| %>
  <%= Time.zone.parse(time) %>  <br>
  <% end %>
</div>

<div>
  <br><%= link_to "Scheduled Dispatch Packages(Admin method)", schedule_path %>
  <br><%= link_to "Homepage", root_path %>
</div>